defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: esports_dev

test:
  <<: *defaults
  database: esports_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>